/**
 * Layer 2: 路由规则表（§5 PARAM 联动）
 * 确定性映射：特征 → 主镜片 + 意图 + 标签 + 搜索开关。
 */

import type { PrimaryLens } from './types.js';
import type { IntentFeature } from './intent-feature.js';

export interface RoutingRule {
  id: string;
  match: Partial<IntentFeature>;
  primaryLens: PrimaryLens;
  intent: string;
  tags: string[];
  searchNeed: boolean;
  skill?: string;
  executor?: string;
  postProcess?: string;
  confidenceBoost: number;
  /**
   * 仅用于“门控规则”：match 全部命中时按此值计 base。
   * 图片/文档这类零文本维度规则不能用部分权重评分，否则达不到门控阈值。
   */
  baseConfidence?: number;
  /** 严格要求 match 全部命中，避免只命中高权重字段就产生候选 */
  strictMatch?: boolean;
}

export const ROUTING_TABLE: RoutingRule[] = [
  {
    id: 'R001',
    match: { actionType: 'create', targetDomain: 'code', scope: 'project_level' },
    primaryLens: 'project_manager',
    intent: 'plan',
    tags: ['plan', 'craft', 'must'],
    searchNeed: false,
    executor: 'engineer',
    confidenceBoost: 0.15,
  },
  {
    id: 'R002',
    match: { actionType: 'create', targetDomain: 'document' },
    primaryLens: 'product_manager',
    intent: 'write_doc',
    tags: [],
    searchNeed: false,
    executor: 'content_writer',
    confidenceBoost: 0.2,
  },
  {
    id: 'R002d',
    match: { actionType: 'deep_report' },
    primaryLens: 'project_manager',
    intent: 'deep_report',
    tags: ['deep_report', 'craft'],
    searchNeed: true,
    confidenceBoost: 0.2,
  },
  {
    id: 'R003',
    match: { actionType: 'create', targetDomain: 'code', scope: 'atomic' },
    primaryLens: 'architect',
    intent: 'execute',
    tags: ['craft'],
    searchNeed: false,
    executor: 'engineer',
    confidenceBoost: 0.1,
  },
  {
    id: 'R004',
    match: { actionType: 'query', targetDomain: 'schedule', searchSourceHint: 'local_skill' },
    primaryLens: 'secretary',
    intent: 'local_query',
    tags: [],
    searchNeed: false,
    skill: 'calendar_skill',
    executor: 'calendar_skill',
    confidenceBoost: 0.2,
  },
  {
    id: 'R005',
    match: { actionType: 'send', targetDomain: 'message' },
    primaryLens: 'secretary',
    intent: 'send_message',
    tags: [],
    searchNeed: false,
    skill: 'im_dispatch',
    executor: 'im_dispatch',
    confidenceBoost: 0.25,
  },
  {
    id: 'R006',
    match: { actionType: 'analyze', ambiguityFlags: ['missing_referent'] },
    primaryLens: 'owner',
    intent: 'clarify',
    tags: [],
    searchNeed: false,
    confidenceBoost: 0,
  },
  {
    id: 'R_CULTURAL_REFERENCE',
    match: { actionType: 'cultural_reference' },
    primaryLens: 'secretary',
    intent: 'cultural_reference',
    tags: ['culture'],
    searchNeed: false,
    executor: 'knowledge_qa',
    postProcess: 'cultural_reply',
    confidenceBoost: 0.15,
  },
  {
    id: 'R_IMAGE_COLOR',
    match: { hasImage: true, actionType: 'analyze', targetDomain: 'color' },
    primaryLens: 'architect',
    intent: 'color_recognition',
    tags: ['multimodal', 'color'],
    searchNeed: false,
    executor: 'color_recognition',
    confidenceBoost: 0.25,
    baseConfidence: 0.6,
  },
  {
    id: 'R_IMAGE_GENERAL',
    match: { hasImage: true },
    primaryLens: 'secretary',
    intent: 'image_analysis',
    tags: ['multimodal'],
    searchNeed: false,
    executor: 'image_analysis',
    confidenceBoost: 0.2,
    baseConfidence: 0.55,
  },
  {
    id: 'R_DOCUMENT_QA',
    match: { hasDocument: true, actionType: 'qa' },
    primaryLens: 'secretary',
    intent: 'document_qa',
    tags: ['document'],
    searchNeed: false,
    executor: 'document_qa',
    confidenceBoost: 0.25,
  },
  {
    id: 'R_DOCUMENT_SUMMARY',
    match: { hasDocument: true, actionType: 'summarize' },
    primaryLens: 'secretary',
    intent: 'document_summary',
    tags: ['document'],
    searchNeed: false,
    executor: 'document_qa',
    confidenceBoost: 0.25,
  },
  {
    id: 'R_DOCUMENT_STRUCTURE',
    match: { hasDocument: true, actionType: 'extract_structure' },
    primaryLens: 'architect',
    intent: 'document_structure',
    tags: ['document'],
    searchNeed: false,
    executor: 'document_qa',
    confidenceBoost: 0.25,
  },
  // E417：无附件的 extract_structure（如「提取章节结构」）回退联网检索，避免零候选 must_clarify；
  // 有附件时只走 R_DOCUMENT_STRUCTURE，勿与本规则分差过近触发 option_clarify。
  {
    id: 'R_EXTRACT_STRUCTURE_SEARCH',
    match: { actionType: 'extract_structure', hasDocument: false },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'structure'],
    searchNeed: true,
    confidenceBoost: 0.2,
  },
  {
    id: 'R007',
    match: { actionType: 'emergency' },
    primaryLens: 'secretary',
    intent: 'emergency',
    tags: [],
    searchNeed: false,
    confidenceBoost: 0.5,
  },
  {
    id: 'R007A',
    match: { actionType: 'illegal_request' },
    primaryLens: 'secretary',
    intent: 'safety_refusal',
    tags: ['safety'],
    searchNeed: false,
    confidenceBoost: 0.5,
  },
  {
    id: 'R007B',
    match: { actionType: 'property_emergency' },
    primaryLens: 'secretary',
    intent: 'property_emergency',
    tags: ['emergency'],
    searchNeed: false,
    confidenceBoost: 0.5,
  },
  {
    id: 'R_SELF_IDENTITY',
    match: { actionType: 'self_identity' },
    primaryLens: 'secretary',
    intent: 'self_identity',
    tags: ['self'],
    searchNeed: false,
    executor: 'knowledge_qa',
    confidenceBoost: 0.25,
    baseConfidence: 0.65,
  },
  {
    id: 'R008',
    match: { actionType: 'query', targetDomain: 'search', searchSourceHint: 'web_search' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search'],
    searchNeed: true,
    confidenceBoost: 0.3,
  },
  {
    id: 'R009',
    match: { actionType: 'create', targetDomain: 'document', scope: 'atomic' },
    primaryLens: 'product_manager',
    intent: 'write_doc',
    tags: ['craft'],
    searchNeed: false,
    executor: 'content_writer',
    confidenceBoost: 0.2,
  },
  {
    id: 'R010',
    match: { actionType: 'analyze', targetDomain: 'finance' },
    primaryLens: 'owner',
    intent: 'cost_analysis',
    tags: [],
    searchNeed: false,
    confidenceBoost: -0.15,
  },
  {
    id: 'R012',
    match: { actionType: 'unknown' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search'],
    searchNeed: true,
    confidenceBoost: 0.3,
  },
  {
    id: 'R13',
    match: { actionType: 'analyze', targetDomain: 'security' },
    primaryLens: 'owner',
    intent: 'risk_review',
    tags: ['security'],
    searchNeed: false,
    confidenceBoost: 0.15,
    strictMatch: true,
  },
  {
    id: 'R14',
    match: {
      actionType: 'schedule',
      targetDomain: 'schedule',
      hasTimeExpression: true,
    },
    primaryLens: 'secretary',
    intent: 'create_calendar',
    tags: ['schedule'],
    searchNeed: false,
    executor: 'calendar_skill',
    confidenceBoost: 0.15,
    strictMatch: true,
  },
  {
    id: 'R15',
    match: {
      actionType: 'compare',
      targetDomain: 'finance',
      searchSourceHint: 'vendor_db',
    },
    primaryLens: 'owner',
    intent: 'compare_vendor_quotes',
    tags: ['finance'],
    searchNeed: false,
    executor: 'quote_compare',
    confidenceBoost: 0.15,
    strictMatch: true,
  },
  {
    id: 'R016',
    match: { actionType: 'qa' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'qa'],
    searchNeed: true,
    confidenceBoost: 0.2,
  },
  {
    id: 'R017',
    match: { actionType: 'analyze', hasGithubLink: true },
    primaryLens: 'secretary',
    intent: 'github_analysis',
    tags: ['github'],
    searchNeed: false,
    skill: 'github-reader',
    executor: 'github_reader',
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R018',
    match: { actionType: 'compare', targetDomain: 'code' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'compare'],
    searchNeed: true,
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R018A',
    match: { actionType: 'compare' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'compare'],
    searchNeed: true,
    confidenceBoost: 0.2,
    strictMatch: true,
  },
  {
    id: 'R019',
    match: { actionType: 'summarize', hasDocument: false },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'summarize'],
    searchNeed: true,
    confidenceBoost: 0.2,
    strictMatch: true,
  },
  {
    id: 'R020',
    match: { actionType: 'rewrite' },
    primaryLens: 'secretary',
    intent: 'rewrite',
    tags: ['rewrite'],
    searchNeed: false,
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R021',
    match: { actionType: 'pack' },
    primaryLens: 'secretary',
    intent: 'pack_project',
    tags: ['pack'],
    searchNeed: false,
    skill: 'project-packager',
    executor: 'project_packager',
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R022',
    match: { actionType: 'modify', targetDomain: 'code' },
    primaryLens: 'architect',
    intent: 'execute',
    tags: ['craft'],
    searchNeed: false,
    executor: 'engineer',
    confidenceBoost: 0.2,
    strictMatch: true,
  },
  {
    id: 'R023',
    match: { actionType: 'operate', targetDomain: 'system' },
    primaryLens: 'project_manager',
    intent: 'execute',
    tags: ['mcp', 'system'],
    searchNeed: false,
    executor: 'mcp_agent',
    confidenceBoost: 0.2,
    strictMatch: true,
  },
  {
    id: 'R_BOM',
    match: { actionType: 'generate_bom', hasDocument: true },
    primaryLens: 'secretary',
    intent: 'generate_bom',
    tags: ['life', 'document'],
    searchNeed: false,
    executor: 'schematic_bom',
    confidenceBoost: 0.2,
    baseConfidence: 0.6,
  },
  {
    id: 'R_OFFICE_DAILY',
    match: { actionType: 'office_daily' },
    primaryLens: 'secretary',
    intent: 'office_daily',
    tags: ['life', 'office'],
    searchNeed: false,
    executor: 'office_daily',
    confidenceBoost: 0.3,
    baseConfidence: 0.6,
  },
  {
    id: 'R_LEARN_VIDEO',
    match: { actionType: 'learn_video' },
    primaryLens: 'secretary',
    intent: 'learn_video',
    tags: ['video', 'learning'],
    searchNeed: false,
    executor: 'video_learner',
    confidenceBoost: 0.3,
    baseConfidence: 0.6,
  },
  // E340：Xmind 思维导图（PM 角色）——actionType-only strict 命中；中带置信度走 confirm，
  // 写类 pm_xmind 执行器在 pipeline 挂起等批准（读 .xmind 同一低风险闸门）
  // E342：内容型思维导图（主题 + 思维导图、无自带大纲）→ 检索 + LLM 出大纲，再挂生成 .xmind 裁决卡
  {
    id: 'R_XMIND_CONTENT',
    match: { actionType: 'xmind_content' },
    primaryLens: 'project_manager',
    intent: 'xmind_content',
    tags: ['pm', 'xmind', 'content'],
    searchNeed: true,
    confidenceBoost: 0.15,
    baseConfidence: 0.55,
    strictMatch: true,
  },
  {
    id: 'R_XMIND',
    match: { actionType: 'xmind' },
    primaryLens: 'project_manager',
    intent: 'xmind',
    tags: ['pm', 'xmind'],
    searchNeed: false,
    executor: 'pm_xmind',
    confidenceBoost: 0.15,
    baseConfidence: 0.55,
    strictMatch: true,
  },
  // E353：CodeGraph 本地代码影响/调用/项目解读（架构师/工程开发）——只读本地工具，
  // 无写副作用 → 不进 confirm 写类清单；索引缺失时 skill 内给 init 引导
  {
    id: 'R_CODEGRAPH',
    match: { actionType: 'codegraph_impact' },
    primaryLens: 'architect',
    intent: 'codegraph_impact',
    tags: ['code', 'architect', 'impact'],
    searchNeed: false,
    executor: 'codegraph',
    confidenceBoost: 0.2,
    baseConfidence: 0.7,
    strictMatch: true,
  },
  // E364：分层架构/框架/模块图（layered-arch 自研 viewer，替代 Archify 架构类）——写类执行器，
  // decision=confirm 时由 pipeline 挂起等批准（content_generation 成本口径）
  {
    id: 'R_LAYERED_ARCH',
    match: { actionType: 'layered_arch_diagram' },
    primaryLens: 'architect',
    intent: 'layered_arch_diagram',
    tags: ['diagram', 'architect'],
    searchNeed: false,
    executor: 'layered_arch',
    confidenceBoost: 0.15,
    baseConfidence: 0.55,
    strictMatch: true,
  },
  // E352：Archify 系统/流程/时序/数据流/生命周期交互图（架构师角色）——写类执行器，
  // decision=confirm 时由 pipeline 挂起等批准（content_generation 成本口径）
  {
    id: 'R_ARCHIFY',
    match: { actionType: 'archify_diagram' },
    primaryLens: 'architect',
    intent: 'archify_diagram',
    tags: ['diagram', 'architect'],
    searchNeed: false,
    executor: 'archify',
    confidenceBoost: 0.15,
    baseConfidence: 0.55,
    strictMatch: true,
  },
  {
    id: 'R_CHAT',
    match: { actionType: 'chat' },
    primaryLens: 'secretary',
    intent: 'companion_chat',
    tags: ['life'],
    searchNeed: false,
    confidenceBoost: 0.3,
  },
  {
    id: 'R_APPLY_TO_PROJECT',
    match: { actionType: 'apply_to_project' },
    primaryLens: 'project_manager',
    intent: 'apply_to_project',
    tags: ['project', 'execute'],
    searchNeed: false,
    executor: 'project_writer',
    confidenceBoost: 0.3,
  },
];
