/**
 * Layer 2: 路由规则表（§5 PARAM 联动）
 * 确定性映射：特征 → 主镜片 + 意图 + 标签 + 搜索开关。
 */

import type { PrimaryLens } from './types.js';
import type { IntentFeature } from './intent-feature.js';

export interface RoutingRule {
  id: string;
  match: Partial<IntentFeature>;
  primaryLens: PrimaryLens;
  intent: string;
  tags: string[];
  searchNeed: boolean;
  skill?: string;
  executor?: string;
  postProcess?: string;
  confidenceBoost: number;
  /**
   * 仅用于“门控规则”：match 全部命中时按此值计 base。
   * 图片/文档这类零文本维度规则不能用部分权重评分，否则达不到门控阈值。
   */
  baseConfidence?: number;
  /** 严格要求 match 全部命中，避免只命中高权重字段就产生候选 */
  strictMatch?: boolean;
}

export const ROUTING_TABLE: RoutingRule[] = [
  {
    id: 'R001',
    match: { actionType: 'create', targetDomain: 'code', scope: 'project_level' },
    primaryLens: 'project_manager',
    intent: 'plan',
    tags: ['plan', 'craft', 'must'],
    searchNeed: false,
    executor: 'engineer',
    confidenceBoost: 0.15,
  },
  {
    id: 'R002',
    match: { actionType: 'create', targetDomain: 'document' },
    primaryLens: 'product_manager',
    intent: 'write_doc',
    tags: [],
    searchNeed: false,
    executor: 'content_writer',
    confidenceBoost: 0.2,
  },
  {
    id: 'R003',
    match: { actionType: 'create', targetDomain: 'code', scope: 'atomic' },
    primaryLens: 'architect',
    intent: 'execute',
    tags: ['craft'],
    searchNeed: false,
    executor: 'engineer',
    confidenceBoost: 0.1,
  },
  {
    id: 'R004',
    match: { actionType: 'query', targetDomain: 'schedule', searchSourceHint: 'local_skill' },
    primaryLens: 'secretary',
    intent: 'local_query',
    tags: [],
    searchNeed: false,
    skill: 'calendar_skill',
    executor: 'calendar_skill',
    confidenceBoost: 0.2,
  },
  {
    id: 'R005',
    match: { actionType: 'send', targetDomain: 'message' },
    primaryLens: 'secretary',
    intent: 'send_message',
    tags: [],
    searchNeed: false,
    skill: 'im_dispatch',
    executor: 'im_dispatch',
    confidenceBoost: 0.25,
  },
  {
    id: 'R006',
    match: { actionType: 'analyze', ambiguityFlags: ['missing_referent'] },
    primaryLens: 'owner',
    intent: 'clarify',
    tags: [],
    searchNeed: false,
    confidenceBoost: 0,
  },
  {
    id: 'R_CULTURAL_REFERENCE',
    match: { actionType: 'cultural_reference' },
    primaryLens: 'secretary',
    intent: 'cultural_reference',
    tags: ['culture'],
    searchNeed: false,
    executor: 'knowledge_qa',
    postProcess: 'cultural_reply',
    confidenceBoost: 0.15,
  },
  {
    id: 'R_IMAGE_COLOR',
    match: { hasImage: true, actionType: 'analyze', targetDomain: 'color' },
    primaryLens: 'architect',
    intent: 'color_recognition',
    tags: ['multimodal', 'color'],
    searchNeed: false,
    executor: 'color_recognition',
    confidenceBoost: 0.25,
    baseConfidence: 0.6,
  },
  {
    id: 'R_IMAGE_GENERAL',
    match: { hasImage: true },
    primaryLens: 'secretary',
    intent: 'image_analysis',
    tags: ['multimodal'],
    searchNeed: false,
    executor: 'image_analysis',
    confidenceBoost: 0.2,
    baseConfidence: 0.55,
  },
  {
    id: 'R_DOCUMENT_QA',
    match: { hasDocument: true, actionType: 'qa' },
    primaryLens: 'secretary',
    intent: 'document_qa',
    tags: ['document'],
    searchNeed: false,
    executor: 'document_qa',
    confidenceBoost: 0.25,
  },
  {
    id: 'R_DOCUMENT_SUMMARY',
    match: { hasDocument: true, actionType: 'summarize' },
    primaryLens: 'secretary',
    intent: 'document_summary',
    tags: ['document'],
    searchNeed: false,
    executor: 'document_qa',
    confidenceBoost: 0.25,
  },
  {
    id: 'R_DOCUMENT_STRUCTURE',
    match: { hasDocument: true, actionType: 'extract_structure' },
    primaryLens: 'architect',
    intent: 'document_structure',
    tags: ['document'],
    searchNeed: false,
    executor: 'document_qa',
    confidenceBoost: 0.25,
  },
  {
    id: 'R007',
    match: { actionType: 'emergency' },
    primaryLens: 'secretary',
    intent: 'emergency',
    tags: [],
    searchNeed: false,
    confidenceBoost: 0.5,
  },
  {
    id: 'R007A',
    match: { actionType: 'illegal_request' },
    primaryLens: 'secretary',
    intent: 'safety_refusal',
    tags: ['safety'],
    searchNeed: false,
    confidenceBoost: 0.5,
  },
  {
    id: 'R007B',
    match: { actionType: 'property_emergency' },
    primaryLens: 'secretary',
    intent: 'property_emergency',
    tags: ['emergency'],
    searchNeed: false,
    confidenceBoost: 0.5,
  },
  {
    id: 'R008',
    match: { actionType: 'query', targetDomain: 'search', searchSourceHint: 'web_search' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search'],
    searchNeed: true,
    confidenceBoost: 0.3,
  },
  {
    id: 'R009',
    match: { actionType: 'create', targetDomain: 'document', scope: 'atomic' },
    primaryLens: 'product_manager',
    intent: 'write_doc',
    tags: ['craft'],
    searchNeed: false,
    executor: 'content_writer',
    confidenceBoost: 0.2,
  },
  {
    id: 'R010',
    match: { actionType: 'analyze', targetDomain: 'finance' },
    primaryLens: 'owner',
    intent: 'cost_analysis',
    tags: [],
    searchNeed: false,
    confidenceBoost: -0.15,
  },
  {
    id: 'R012',
    match: { actionType: 'unknown' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search'],
    searchNeed: true,
    confidenceBoost: 0.3,
  },
  {
    id: 'R13',
    match: { actionType: 'analyze', targetDomain: 'security' },
    primaryLens: 'owner',
    intent: 'risk_review',
    tags: ['security'],
    searchNeed: false,
    confidenceBoost: 0.15,
    strictMatch: true,
  },
  {
    id: 'R14',
    match: {
      actionType: 'schedule',
      targetDomain: 'schedule',
      hasTimeExpression: true,
    },
    primaryLens: 'secretary',
    intent: 'create_calendar',
    tags: ['schedule'],
    searchNeed: false,
    executor: 'calendar_skill',
    confidenceBoost: 0.15,
    strictMatch: true,
  },
  {
    id: 'R15',
    match: {
      actionType: 'compare',
      targetDomain: 'finance',
      searchSourceHint: 'vendor_db',
    },
    primaryLens: 'owner',
    intent: 'compare_vendor_quotes',
    tags: ['finance'],
    searchNeed: false,
    executor: 'quote_compare',
    confidenceBoost: 0.15,
    strictMatch: true,
  },
  {
    id: 'R016',
    match: { actionType: 'qa' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'qa'],
    searchNeed: true,
    confidenceBoost: 0.2,
  },
  {
    id: 'R017',
    match: { actionType: 'analyze', hasGithubLink: true },
    primaryLens: 'secretary',
    intent: 'github_analysis',
    tags: ['github'],
    searchNeed: false,
    skill: 'github-reader',
    executor: 'github_reader',
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R018',
    match: { actionType: 'compare', targetDomain: 'code' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'compare'],
    searchNeed: true,
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R018A',
    match: { actionType: 'compare' },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'compare'],
    searchNeed: true,
    confidenceBoost: 0.2,
    strictMatch: true,
  },
  {
    id: 'R019',
    match: { actionType: 'summarize', hasDocument: false },
    primaryLens: 'secretary',
    intent: 'web_search',
    tags: ['search', 'summarize'],
    searchNeed: true,
    confidenceBoost: 0.2,
    strictMatch: true,
  },
  {
    id: 'R020',
    match: { actionType: 'rewrite' },
    primaryLens: 'secretary',
    intent: 'rewrite',
    tags: ['rewrite'],
    searchNeed: false,
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R021',
    match: { actionType: 'pack' },
    primaryLens: 'secretary',
    intent: 'pack_project',
    tags: ['pack'],
    searchNeed: false,
    skill: 'project-packager',
    executor: 'project_packager',
    confidenceBoost: 0.25,
    strictMatch: true,
  },
  {
    id: 'R022',
    match: { actionType: 'modify', targetDomain: 'code' },
    primaryLens: 'architect',
    intent: 'execute',
    tags: ['craft'],
    searchNeed: false,
    executor: 'engineer',
    confidenceBoost: 0.2,
    strictMatch: true,
  },
];
